### ISSUE TITLE
List other links to describe how to join us when there is an outage

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/docker-404#12]
Currently it tells to go to an internal page for contacting us, which is unfortunate:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/91831478/142423744-e9c2184c-3eac-4ede-b8f9-6682654a974d.png">

**Comment by tanujdevops** [comment]
> Currently it tells to go to an internal page for contacting us, which is unfortunate:
> 
> <img width="730" alt="image" src="https://user-images.githubusercontent.com/91831478/142423744-e9c2184c-3eac-4ede-b8f9-6682654a974d.png">
> 

Hello Sir.
I'm Tanuj, I'm an undergraduate student and I'm just getting started with Open Source. 
I'd like to help resolve this issue.
Can you please tell me what I exactly need to do with a little more details so that I can help resolving this issue?

**Comment by KitsuneKode** [comment]
What are the additional links to be added? github issues? community and forum?

![image](https://github.com/user-attachments/assets/1ea2bb24-34da-495b-9e2c-eee16ac81615)

all of these except mailing list?

**Comment by lemeurherve** [comment]
I'd say #jenkins-infra Matrix channel and https://github.com/jenkins-infra/helpdesk/

@dduportal @smerle33 WDYT?

**Comment by dduportal** [comment]
Yep: Github helpdesk and Matrix channel.

Also: the jenkins-infra mailing list

**Comment by dduportal** [comment]
Closed by #37 

Thanks for your contribution @KitsuneKode !
