### ISSUE TITLE
Job on trusted.ci.jenkins.io fails consistently for this repository

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/docker-404#9]
It seems like the execution of this may have moved from trusted.ci.jenkins.io to https://infra.ci.jenkins.io/job/Docker%20Builds/job/docker-404/job/main/ .  Should it be deleted from trusted.ci.jenkins.io?

https://trusted.ci.jenkins.io:1443/job/Containers/job/404/ is configured to poll every 15 minutes from trusted.ci.jenkins.io .  The last time it succeeded was Apr 26, 2021 as far as I can tell.  

The job configuration on trusted.ci.jenkins.io is looking for a branch named `master`, while this repository uses `main` as its default branch.

The job configuration on trusted.ci.jenkins.io is looking for a pipeline definition file named `Jenkinsfile` while the main branch has a pipeline definition file named `Jenkinsfile_k8s`.

The job configuration on trusted.ci.jenkins.io cannot find a necessary plugin or some other necessary component.  When run from the `main` branch with the pipeline definition in `Jenkinsfile_k8s`, it reports `java.lang.NoSuchMethodError: No such DSL method 'podAnnotation' found among steps`.

**Comment by dduportal** [comment]
Hello! Your diagnosis is correct: we can safely remove the  job from trusted.ci, as infra.ci is the system in charge of CI and CD for this image, since the 28th of April 2021.

We forgot to delete this job from trusted, sorry for this.

**Comment by MarkEWaite** [comment]
Deleted.  Thanks for the confirmation @dduportal
